"""
Conversation State Models
==========================
Implements the CoE-SQL (Chain of Editions) conversation pattern (ADR-008).

Instead of passing raw chat history to the LLM, UADA maintains a typed
ConversationState. Each turn records the resolved intent, query plan,
and a compact summary — not the full chat transcript.

The "edition" concept: each turn is either a new query or a modification
of a prior query. The Conversation Manager tracks what changed (the diff),
not just what was said.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field

from uada.models.intent import AnalyticalIntent


class TurnStatus(str, Enum):
    SUCCESS = "success"
    ERROR = "error"
    CLARIFICATION_REQUESTED = "clarification_requested"
    SECURITY_REJECTED = "security_rejected"


class ConversationTurn(BaseModel):
    """
    A single turn in a conversation.
    Records everything needed to understand what was asked and what happened.
    """

    turn_id: int = Field(ge=0)
    timestamp: datetime

    # ── User input ────────────────────────────────────────────────────────────
    user_question: str
    status: TurnStatus

    # ── Pipeline artifacts (stored for context and evaluation) ────────────────
    resolved_intent: AnalyticalIntent | None = None
    generated_sql: str | None = None

    # ── Compact context for injection into future turns ───────────────────────
    result_summary: str | None = Field(
        default=None,
        description="Compact summary of the result. E.g. '12 rows — revenue range $12K–$890K. "
        "Top region: West ($320K).' Injected into future prompts instead of raw data.",
    )
    tables_used: list[str] = Field(default_factory=list)
    active_measures: list[str] = Field(
        default_factory=list,
        description="Measures computed in this turn. Carried forward as context.",
    )
    active_dimensions: list[str] = Field(
        default_factory=list,
        description="Dimensions grouped by in this turn. Carried forward as context.",
    )
    active_filters: list[str] = Field(
        default_factory=list,
        description="Semantic filters applied in this turn. "
        "Accumulated across turns for follow-up resolution. "
        "E.g. ['customer_segment = Enterprise', 'region = West']",
    )
    chart_type: str | None = None

    # ── Edition tracking (CoE-SQL) ────────────────────────────────────────────
    edition_diff: str | None = Field(
        default=None,
        description="What changed from the prior turn. "
        "E.g. 'Added filter: customer_segment = Enterprise.' "
        "Empty for the first turn or a completely new query.",
    )

    # ── Error context ─────────────────────────────────────────────────────────
    error_type: str | None = None
    user_facing_error: str | None = None
    clarification_question: str | None = None


class ConversationState(BaseModel):
    """
    The complete state of a conversation session.

    Persisted across requests. Loaded at the start of each turn
    and saved at the end (even if the turn failed).

    Context window management:
    - The last `max_turns` turns are kept in full.
    - Older turns are compressed into `compressed_context`.
    - `active_context` always reflects the current accumulated state.
    """

    session_id: str
    database_id: str = Field(
        description="Identifier of the connected database. "
        "Used to validate that follow-up questions reference the correct schema.",
    )
    created_at: datetime
    last_updated: datetime

    # ── Turn history ──────────────────────────────────────────────────────────
    turns: list[ConversationTurn] = Field(default_factory=list)

    # ── Accumulated context (always current) ──────────────────────────────────
    active_context: ActiveContext = Field(
        default_factory=lambda: ActiveContext(),
        description="Current accumulated analytical context. "
        "Updated after every successful turn.",
    )

    # ── Compressed older context ──────────────────────────────────────────────
    compressed_context: str | None = Field(
        default=None,
        description="Compressed summary of turns beyond max_turns. "
        "Generated by context compression when the session grows long.",
    )

    @property
    def turn_count(self) -> int:
        return len(self.turns)

    @property
    def last_successful_turn(self) -> ConversationTurn | None:
        for turn in reversed(self.turns):
            if turn.status == TurnStatus.SUCCESS:
                return turn
        return None

    def get_recent_turns(self, n: int = 6) -> list[ConversationTurn]:
        """Returns the n most recent turns, oldest first."""
        return self.turns[-n:]

    def get_edition_context(self) -> str:
        """
        Returns a compact, structured description of what has been established
        in this conversation. Injected into Intent Extractor and SQL Generator prompts.

        Format designed to be token-efficient and LLM-readable.
        """
        lines: list[str] = []

        if self.compressed_context:
            lines.append(f"Earlier context: {self.compressed_context}")

        recent = self.get_recent_turns(3)
        for turn in recent:
            if turn.status == TurnStatus.SUCCESS:
                line = f"Turn {turn.turn_id}: '{turn.user_question}'"
                if turn.result_summary:
                    line += f" → {turn.result_summary}"
                if turn.edition_diff:
                    line += f" [Changed: {turn.edition_diff}]"
                lines.append(line)

        ctx = self.active_context
        if ctx.accumulated_filters:
            lines.append(f"Active filters: {', '.join(ctx.accumulated_filters)}")
        if ctx.current_measures:
            lines.append(f"Current measures: {', '.join(ctx.current_measures)}")
        if ctx.current_dimensions:
            lines.append(f"Current dimensions: {', '.join(ctx.current_dimensions)}")

        return "\n".join(lines) if lines else "No prior context."


class ActiveContext(BaseModel):
    """
    The accumulated analytical context that is currently in effect.
    Updated after every successful turn.
    This is the authoritative state of "what we're looking at."
    """

    # What is currently being measured
    current_measures: list[str] = Field(default_factory=list)

    # How results are currently grouped
    current_dimensions: list[str] = Field(default_factory=list)

    # Filters that are currently in effect (accumulated across turns)
    accumulated_filters: list[str] = Field(
        default_factory=list,
        description="Filters accumulated across turns. "
        "Follow-up 'only enterprise customers' adds to this list. "
        "The user can reset by starting a completely new query.",
    )

    # Time context currently in effect
    current_time_range: str | None = None

    # Tables currently referenced
    current_tables: list[str] = Field(default_factory=list)

    # The SQL from the last successful turn (for repair context)
    last_successful_sql: str | None = None
